# Custom cargo configuration

[build]
# Sets the target to our custom toolchain
target = "x86_64-blog_os.json"

[unstable]
# Allows Rust to recompile `core` and other standard library crates on demand
# using the `x86_64-blog_os` target.
build-std = ["core", "compiler_builtins"]

# Implementations for C memory functions that are necessary for the kernel
build-std-features = ["compiler-builtins-mem"]